# Generated by Django 4.0.6 on 2022-08-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('mailid', models.EmailField(max_length=80)),
                ('phoneno', models.IntegerField(max_length=10)),
            ],
        ),
    ]
