# Generated by Django 4.0.6 on 2022-08-18 12:55

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=70, validators=[core.models.emchk]),
        ),
        migrations.AlterField(
            model_name='person',
            name='pno',
            field=models.BigIntegerField(primary_key=True, serialize=False, validators=[core.models.pnochk]),
        ),
        migrations.AlterField(
            model_name='person',
            name='pwd',
            field=models.CharField(max_length=10, validators=[core.models.pwcheck]),
        ),
    ]
